version: "2.3"

service:
  transport_counting:
    image: transport_counting
    continer_name: transport_counting
    working_dir: /transport_counting
    build:
      context: .
    environment:
      - DISPLAY=unix$DISPLAY
    command: python3 -u vehicle_detection_main.py
    volumes:
      - ./:/vehicle_counting
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
